name: slack_notifier
description: A simple wrapper to post messages from external sources into Slack.
version: 0.0.1
homepage: https://github.com/javoeria/slack-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.1

dev_dependencies:
  test: ^1.14.7
