name: slack_notifier
description: A simple wrapper to post messages from external sources into Slack.
version: 1.2.0
homepage: https://github.com/javoeria/slack-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
