name: slack_notifier
description: A simple wrapper to post messages from external sources into Slack.
version: 1.1.0
homepage: https://github.com/javoeria/slack-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.6
